name: Shravik
description: A new Flutter project.

version: 1.0.1+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons:

  firebase_core:
  firebase_analytics:
  cloud_firestore:
  url_launcher: ^5.4.11
  geolocator: ^5.3.2+2
  permission_handler: ^5.0.1+1
  geocoder: ^0.2.1
  firebase_storage:
  image_cropper: 
  image_picker: 
  flutter_image_compress: ^0.7.0
  carousel_slider: ^2.2.1
  share: ^0.6.4+3
  flutter_map:
  multiselect_formfield: ^0.1.3
  location: ^3.0.2
  cached_network_image: ^2.2.0+1
  # flutter_otp_text_field: ^0.0.1
  # sms_autofill: ^1.2.1
  # pin_input_text_field: ^3.0.4

  firebase_auth:
  # google_sign_in:
  # apple_sign_in:

  provider:
  shared_preferences:
  # upstate:

  flutter_platform_widgets:
  flutter_sheet_localization: ^1.0.0
  simple_gravatar:
  # flutter_auth_buttons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_sheet_localization_generator: ^1.0.0
  build_runner: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/default.png
    - assets/images/defaultDark.png
